### ISSUE TITLE
Not works with v49700

### ISSUE THREAD

**Issue by lmet** [999LV/NUT_UPS#5]
Hi,
Since migrating to v49700 the plugin no longer appears in the list of plugins available in domoticz.
I asked for help on the forum without result
Thanks in advance

**Comment by 999LV** [comment]
Here is not the right place as this most likely is a domoticz issue (the plugin did not change). Did you try the usual remedies that can solve domoticz upgrade issues : clear browser cache and app cache, check if certain compressed js files from earlier versions still exist in domoticz/www folder (see forum for help with that), etc.... last resort, try also incognito mode on your browser... if nothing of that works, you will need to check domoticz logs
