### ISSUE TITLE
Domoticz Version 4.9701 : 'onStart' failed 'KeyError' - Line 89 & 199 function onStart

### ISSUE THREAD

**Issue by Dim3333** [999LV/NUT_UPS#6]
Hi,

Domoticz Version 4.9701
Error in Log : 
'onStart' failed 'KeyError' - Line 89 & 199 function onStart

**Comment by Dim3333** [comment]
The device 'UPS Status Mode' is not created.

**Comment by 999LV** [comment]
Did you allow domoticz to create new devices (checkbox in settings page)

**Comment by Dim3333** [comment]
Hi,

I'm stupid. It's OK. All works. Sorry.
